trigger:
- main

pool:
  name: 'default'
  demands:
    - Agent.Name -equals Muneer

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Check PowerShell version
            Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
            
            # Using ConvertTo-SecureString with plain text in PowerShell 7.x
            $secureString = ConvertTo-SecureString "MySecretPassword" -AsPlainText -Force
            Write-Host "Secure string created using ConvertTo-SecureString."

            # Alternative method using System.Security.SecureString
            $secureStringAlt = New-Object System.Security.SecureString
            "mySecretPassword".ToCharArray() | ForEach-Object { $secureStringAlt.AppendChar($_) }
            $secureStringAlt.MakeReadOnly()
            Write-Host "Secure string created using System.Security.SecureString."
            
            # Test writing to console
            Write-Host "Hello World"
      - task: Maven@4
        inputs:
          mavenPomFile: 'JAVa/pom.xml'
          goals: 'clean install'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)\JAVa\target'
          Contents: '**/*.jar'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'