# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'      # Pool name (Default is the Azure DevOps default agent pool)
  demands:
    - agent.name -equals Muneer   # Specific self-hosted agent name

steps:
- script: echo "This pipeline is running on the self-hosted agent named 'Muneer'"
