trigger:
  branches:
    include:
    - main
pool:
  name: 'default'
  demands:
  - Agent.Name -equals Linux

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      inputs:
        containerRegistry: 'Muneeracrregistry'
        command: 'login'
        addBaseImageData: 
    - task: Docker@2
      inputs:
        containerRegistry: 'Muneeracrregistry'
        command: 'build'
        Dockerfile: '**/Dockerfile'