# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'private'          # Your private agent pool name
  demands:
    - Agent.Name -equals Muneerpasha

stages:
  - stage: terraform
    displayName: Terrafom
    jobs:
      - job: terraform
        displayName: 'azure VM using terraform'
        steps:
        
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Free Trial(ecd6e0a6-0b59-4f25-b4e0-d374d995357e)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'Az login'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)Dev_terraform'
            backendServiceArm: 'Free Trial(ecd6e0a6-0b59-4f25-b4e0-d374d995357e)'
            backendAzureRmResourceGroupName: 'DefaultResourceGroup-CCAN'
            backendAzureRmStorageAccountName: 'terraform127'
            backendAzureRmContainerName: 'muneer-az'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)Dev_terraform'
            environmentServiceNameAzureRM: 'Free Trial(ecd6e0a6-0b59-4f25-b4e0-d374d995357e)'