# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'private'          # Your private agent pool name
  demands:
    - Agent.Name -equals Muneerpasha
variables:
  # Azure Service Principal credentials as pipeline variables
  azureClientId: $(azureClientId)  # Store these as pipeline variables
  azureClientSecret: $(azureClientSecret)
  azureTenantId: $(azureTenantId)
  azureSubscriptionId: $(azureSubscriptionId)

stages:
  - stage: terraform
    displayName: Terrafom
    jobs:
      - job: terraform
        displayName: 'azure VM using terraform'
        steps:
        
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Free Trial(ecd6e0a6-0b59-4f25-b4e0-d374d995357e)'
            ScriptType: 'InlineScript'
            Inline: |
              $clientId = "$(azureClientId)"
                    $tenantId = "$(azureTenantId)"
                    $clientSecret = "$(azureClientSecret)"
              
                    # Convert the Client Secret to SecureString
                    $secureClientSecret = ConvertTo-SecureString $clientSecret -AsPlainText -Force
              
                    # Create the credentials object
                    $creds = New-Object System.Management.Automation.PSCredential($clientId, $secureClientSecret)
              
                    # Authenticate to Azure using the Service Principal
                    Connect-AzAccount -ServicePrincipal -TenantId $tenantId -Credential $creds
              
                    # Set the Azure context to the desired subscription
                    Set-AzContext -SubscriptionId "$(azureSubscriptionId)"
              
                    # Verify connection by fetching the subscription details
                    Get-AzSubscription
            azurePowerShellVersion: 'LatestVersion'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)Dev_terraform'
            backendServiceArm: 'Free Trial(ecd6e0a6-0b59-4f25-b4e0-d374d995357e)'
            backendAzureRmResourceGroupName: 'DefaultResourceGroup-CCAN'
            backendAzureRmStorageAccountName: 'terraform127'
            backendAzureRmContainerName: 'muneer-az'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)Dev_terraform'
            environmentServiceNameAzureRM: 'Free Trial(ecd6e0a6-0b59-4f25-b4e0-d374d995357e)'