trigger:
  branches:
    include:
    - main
pool:
  name: 'private'
  demands:
  - Agent.Name -equals Muneerpasha
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Muneeracrregistry'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
