trigger:
- main  # Replace 'main' with your branch name if needed

pool:
  name: 'default'          # Your private agent pool name
  demands:
    - Agent.Name -equals Muneer
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Mysqlconnector
    displayName: 'Mysqlconnector'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '5.8'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'ASP.NET/mysql-connector-net/EFCore/MySql.EntityFrameworkCore.sln'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'ASP.NET/mysql-connector-net/EntityFramework/MySql.Data.EntityFramework.sln'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'ASP.NET/mysql-connector-net/MySQL.Data.OpenTelemetry/MySQL.Data.OpenTelemetry.sln'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'ASP.NET/mysql-connector-net/MySQL.Data/MySql.Data.sln'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'ASP.NET/mysql-connector-net/MySql.Web/MySql.Web.sln'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.sln'
        arguments: '-configuration $(buildConfiguration)'
        testRunTitle: 'MySQL Connector Tests'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'