# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0613293d-db0d-466e-be2b-6392ac62d2c7'
  imageRepository: 'muneer'
  containerRegistry: 'muneeracrregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfiles/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'private'
  demands:
  - Agent.Name -equals Muneerpasha

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
