trigger:
  branches:
    include:
    - main
pool:
  name: 'private'
  demands:
  - Agent.Name -equals Muneerpasha
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: terraform
    displayName: 'youtube clone'
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
        checkLatest: true
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'Youtube_Clone'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'Youtube_Clone'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    
  

  