trigger:
  branches:
    include:
    - main
pool:
  name: 'private'
  demands:
  - Agent.Name -equals Muneerpasha
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: terraform
    displayName: 'youtube clone'
  

  